Update Project details
COPS-IITBHU/sdg-site pull request #50
Opened 2022-02-11 18:42 UTC by eshaanagarwal

## Description
- [x] Added Previewer and Discord Bot Details
- [x] Updated images of Lite-hai, Internship portal and Telegram bot

## Fixes
Fixes parts of #45 

## Types of changes

- [ ] Bug/Hot fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring Old Code ( non-breaking change replacing already existing code )
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have read the **CONTRIBUTING** guidelines in repository.
- [x] My pull request has a descriptive title and is attached to an existing issue.
- [x] I haven't repeated the code and it follows established code style of repository.
- [x] My branch is up-to-date with upstream branch.
- [x] All new and existing tests passed.

2022-02-11 18:52 UTC, king-11 requested changes

2022-02-11 18:52 UTC, king-11 commented on content/index/projectData.yml
>      desc: Lite Hai! is a mobile app that acts as a guide for all the gymkhana happenings at IIT BHU.
Can add more info here

2022-02-11 18:52 UTC, king-11 commented on content/index/projectData.yml
>        - Kotlin
Typescript and Vercel

2022-02-11 18:54 UTC, king-11 commented
I will provide image for placement portal, for bots we can call some commands and then show it, lite hai can have better image too @Sriraj-dev can help in that department

2022-02-11 18:56 UTC, king-11 commented
For placement portal use the landing image from here https://www.placement.iitbhu.ac.in/

2022-02-11 19:23 UTC, king-11 commented
The telegram one is getting pixelated let's crop it

2022-02-11 19:32 UTC, eshaanagarwal commented
@king-11 All mobile (vertical) screen shots are getting pixelated. Should i crop all of them ?

2022-02-11 19:32 UTC, king-11 commented
Yeah let's do that for discord bot you can take ss on command from chatroom on desktop/browser

2022-02-12 04:34 UTC, king-11 commented
Apart from telegram bot and study portal rest all images are good 🤔

2022-02-12 09:56 UTC, king-11 approved these changes

2022-02-12 09:56 UTC, merged